[package]
name = "pgmanager"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal", "io-util", "io-std", "net", "time"] }
tokio-util = "0.7.15"
